bundles/BirthdayBundle/Entity/Birthday.php
<?php
/**
 * Created by PhpStorm.
 * User: Tim
 * Date: 28.07.2017
 * Time: 20:41
 */

namespace BirthdayBundle\Entity;

use DateTime;
use Doctrine\ORM\Mapping as ORM;
use Exception;

/**
 * @ORM\Entity(repositoryClass="BirthdayBundle\Repository\Birthday")
 */
class Birthday
{
    /**
     * @ORM\Id
     * @ORM\Column(type="integer")
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    public $id;

    /**
     * @ORM\Column(type="date")
     * @var DateTime
     */
    public $birthdate;


    /**
     * @ORM\Column(type="name",type="string",length=100)
     */
    public $name;

    public function getNextAge()
    {
        $nextBirthday = $this->getNextBirthday()->setTime(2, 0, 0);
        $diff = $this->birthdate->diff($nextBirthday);
        return $diff->y;
    }

    public function getAgeThisYear()
    {
        $nextBirthday = $this->getBirthdayThisYear()->setTime(2, 0, 0);
        $diff = $this->birthdate->diff($nextBirthday);
        return $diff->y;
    }

    public function thisYearBirthdayIsRound()
    {
        $nextAge = $this->getAgeThisYear();
        $quotient = $nextAge / 10;
        return $quotient == round($quotient);
    }

    public function nextBirthdayIsRound()
    {
        $nextAge = $this->getNextAge();
        $quotient = $nextAge / 10;
        return $quotient == round($quotient);
    }

    protected function getNextBirthday()
    {
        $birthday = $this->getBirthdayThisYear();
        $today = $this->getToday();
        if ($birthday < $today) {
            $birthday = $this->getBirthdayNextYear();
        }
        return $birthday;
    }

    protected function getBirthdayThisYear()
    {
        $year = date('Y');
        return $this->getBirthdayForYear($year);
    }

    protected function getBirthdayNextYear()
    {
        $year = date('Y', strtotime('next year'));
        return $this->getBirthdayForYear($year);
    }

    protected function getBirthdayForYear($year)
    {
        try {
            $birthday = new DateTime($year . '-' . $this->birthdate->format('m-d'));
            $birthday->setTime(0, 0, 0);
            return $birthday;
        } catch (Exception $e) {
            return null;
        }
    }

    protected function getToday()
    {
        $today = new DateTime();
        $today->setTime(0, 0, 0);
        return $today;
    }

}

bundles/BirthdayBundle/Controller/BirthdayController.php
<?php

namespace BirthdayBundle\Controller;

use BirthdayBundle\Entity\Birthday;
use BirthdayBundle\Form\BirthdayFormType;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\HttpFoundation\Request;

class BirthdayController extends AbstractController
{
    /**
     * @Route("/birthday", name="birthday")
     * @return Response
     */
    public function indexAction()
    {
        $pastBirthdays = $this->getDoctrine()->getRepository(Birthday::class)->findAllPastOrderedByDay();
        $futureBirthdays = $this->getDoctrine()->getRepository(Birthday::class)->findAllFutureOrderedByDay();
        return $this->render('closed_area/Birthday/index.html.twig', ['pastBirthdays' => $pastBirthdays, 'futureBirthdays' => $futureBirthdays]);
    }

    /**
     * @Route("/birthday/create", name="birthday_create")
     * @param Request $request
     * @return Response
     */
    public function create(Request $request)
    {
        setlocale(LC_TIME, "de_DE");
        $birthday = new Birthday();
        $form = $this->createForm(BirthdayFormType::class, $birthday);
        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {

            $em = $this->getDoctrine()->getManager();
            $em->persist($birthday);
            $em->flush();
            $this->addFlash('success', 'Geburtstag wurde gespeichert!');
            return $this->redirectToRoute('birthday');
        }
        return $this->render('closed_area/Birthday/form.html.twig', ['form' => $form->createView(), 'page_title' => 'Geburtstag hinzufügen']);
    }


    /**
     * @Route("/birthday/edit/{birthday}", name="birthday_edit")
     * @param Birthday $birthday
     * @param Request $request
     * @return Response
     */
    public function edit(Birthday $birthday, Request $request)
    {
        $form = $this->createForm(BirthdayFormType::class, $birthday);
        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {

            $em = $this->getDoctrine()->getManager();
            $em->persist($birthday);
            $em->flush();
            $this->addFlash('success', 'Geburtstag wurde gespeichert!');
            return $this->redirectToRoute('birthday');
        }
        return $this->render('closed_area/Birthday/form.html.twig', ['form' => $form->createView(), 'page_title' => 'Geburtstag bearbeiten']);
    }

    /**
     * @Route("/birthday/delete/{birthday}/{confirm}", name="birthday_delete",defaults={"confirm"=false})
     * @param Birthday $birthday
     * @param bool $confirm
     * @return Response
     */
    public function delete(Birthday $birthday, $confirm = false)
    {
        if ($confirm == false) {
            return $this->render('closed_area/confirm.html.twig', ['type' => 'Geburtstag']);
        }
        $em = $this->getDoctrine()->getManager();
        $em->remove($birthday);
        $em->flush();
        $this->addFlash('success', 'Geburtstag wurde gelöscht!');
        return $this->redirectToRoute('birthday');

    }
}

templates/default/closed_area/Birthday/form.html.twig
{% extends 'closed_area/base.html.twig' %}
{% block content_row %}
    <div class="container container-fluid" id="home">
        <!-- HOME -->

        <!-- ABOUT & UPDATES -->
        <div class="row-fluid" id="about">
            {{ form_start(form) }}
            <div class="span12">
                <h2 class="page-title" id="scroll_up"> {{ page_title }}</h2>
                {{ form_widget(form) }}
            </div>
            <button type="submit" class="btn btn-success" name="_submit">speichern</button>
            <a href="{{ path('birthday') }}" class="btn btn-default" name="_submit">zurück</a>
            {{ form_end(form) }}
        </div>


    </div>
{% endblock %}

templates/default/closed_area/Birthday/index.html.twig
{% extends 'closed_area/base.html.twig' %}
{% block content_row %}
    <div class="container container-fluid" id="home">
        <!-- HOME -->

        <!-- ABOUT & UPDATES -->
        <div class="row-fluid" id="about">
            <div class="span12">
                <h2 class="page-title" id="scroll_up"> Geburtstage</h2>
                <a href="{{ path('birthday_create') }}" class="btn btn-sm btn-success"><span
                            class="glyphicon glyphicon-plus"></span> hinzufügen</a>
                <h3>Dieses Jahr</h3>
                <table class="table table-striped">
                    {% for birthday in futureBirthdays %}
                        <tr>
                            <td>{{ birthday.birthdate|date('d.m.Y') }} <span
                                        class="badge {% if birthday.nextBirthdayIsRound %}success{% endif %}">{{ birthday.nextAge }}</span>
                            </td>
                            <td>{{ birthday.name }}</td>
                            <td><a href="{{ path('birthday_edit',{birthday:birthday.id}) }}"
                                   class="btn btn-sm btn-warning"><span class="glyphicon glyphicon-pencil"></span></a>
                                <a href="{{ path('birthday_delete',{birthday:birthday.id}) }}"
                                   class="btn btn-sm btn-danger"><span class="glyphicon glyphicon-trash"></span></a>
                            </td>
                        </tr>
                    {% endfor %}
                </table>
                <h3>Nächstes Jahr</h3>
                <table class="table table-striped">
                    {% for birthday in pastBirthdays %}
                        <tr>
                            <td>{{ birthday.birthdate|date('d.m.Y') }} <span
                                        class="badge {% if birthday.nextBirthdayIsRound %}success{% endif %}">{{ birthday.nextAge }}</span>
                            </td>
                            <td>{{ birthday.name }}</td>
                            <td><a href="{{ path('birthday_edit',{birthday:birthday.id}) }}"
                                   class="btn btn-sm btn-warning"><span class="glyphicon glyphicon-pencil"></span></a>
                                <a href="{{ path('birthday_delete',{birthday:birthday.id}) }}"
                                   class="btn btn-sm btn-danger"><span class="glyphicon glyphicon-trash"></span></a>
                            </td>
                        </tr>
                    {% endfor %}
                </table>
            </div>

        </div>


    </div>
{% endblock %}

templates/default/closed_area/Birthday/menu.html.twig
<li class="nav-item">
    <a class="nav-link" href="{{ path('birthday') }}">Geburtstage</a>
</li>

templates/default/closed_area/Birthday/view.html.twig
{% extends 'closed_area/base.html.twig' %}
{% block content_row %}
    <div class="container container-fluid" id="home">
        <!-- HOME -->

        <!-- ABOUT & UPDATES -->
        <div class="row-fluid" id="about">
            <div class="col-sm-12">
                <div class="row">
                    <div class="col-sm-12">
                        <h2 class="page-title" id="scroll_up"> Veranstaltung {{ event.name }}</h2>
                        <a href="{{ path('event') }}" class="btn btn-sm btn-default" name="_submit"><span
                                    class="glyphicon glyphicon-backward"></span> zurück</a> <a
                                href="{{ path('event_edit',{event:event.id}) }}" class="btn btn-sm btn-warning"><span
                                    class="glyphicon glyphicon-pencil"></span> bearbeiten</a> <a
                                href="{{ path('event_delete',{event:event.id}) }}" class="btn btn-sm btn-danger"><span
                                    class="glyphicon glyphicon-trash"></span> löschen</a>
                    </div>
                </div>
                <div class="row voffset5">
                    <div class="col-sm-2 viewlabel">Datum:</div>
                    <div class="col-sm-10">{{ event.date|date('d.m.Y H:i') }}</div>
                </div>
                <div class="row voffset3">
                    <div class="col-sm-2 viewlabel">Name:</div>
                    <div class="col-sm-10">{{ event.name }}</div>
                </div>
                <div class="row voffset3">
                    <div class="col-sm-2 viewlabel">Ort:</div>
                    <div class="col-sm-10">{{ event.location }}</div>
                </div>
                <div class="row voffset3">
                    <div class="col-sm-2 viewlabel">Info:</div>
                    <div class="col-sm-10">{{ event.info|nl2br|auto_link_text }}</div>
                </div>
            </div>
        </div>
    </div>


    </div>
{% endblock %}

templates/default/closed_area/Birthday/widget.html.twig
<div class="row-fluid item">
    <div class="col-md-6 updates" id="updates">
        <h2 class="page-title" id="scroll_up"> Geburtstage</h2>
        <!-- UPDATES & RELEASE NOTES -->
        <h3 class="version">Dieser Monat</h3>
        <ul>
            {% if birthday_current_month|length == 0 %}
                <li><i>-- keine --</i></li>
            {% endif %}
            {% for birthday in birthday_current_month %}
                <li>{{ birthday.birthdate|date('d.m') }} {{ birthday.name }} <span
                            class="badge {% if birthday.thisYearBirthdayIsRound %}success{% endif %}">{{ birthday.ageThisYear }}</span>
                </li>
            {% endfor %}
        </ul>
        <h3 class="version">Nächster Monat</h3>
        <ul>
            {% if birthday_next_month|length == 0 %}
                <li><i>-- keine --</i></li>
            {% endif %}
            {% for birthday in birthday_next_month %}
                <li>{{ birthday.birthdate|date('d.m') }} {{ birthday.name }} <span
                            class="badge {% if birthday.nextBirthdayIsRound %}success{% endif %}">{{ birthday.getNextAge }}</span>
                </li>
            {% endfor %}
        </ul>
    </div>
</div>