bundles/EventBundle/Entity/RepeatingEvent.php
<?php


namespace EventBundle\Entity;

use App\Entity\User;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\ORM\Mapping as ORM;
use EventBundle\Enums\RepeatingType;
use Gedmo\Mapping\Annotation as Gedmo;
use Gedmo\SoftDeleteable\Traits\SoftDeleteableEntity;
use Symfony\Component\Security\Core\User\UserInterface;

/**
 * @ORM\Entity(repositoryClass="EventBundle\Repository\RepeatingEvent")
 * @ORM\HasLifecycleCallbacks()
 * @Gedmo\SoftDeleteable(fieldName="deletedAt", timeAware=false)
 */
class RepeatingEvent
{
    use SoftDeleteableEntity;

    /**
     * @ORM\Id
     * @ORM\Column(name="id", type="guid",options={"collation":"utf8_unicode_ci"})
     * @ORM\GeneratedValue(strategy="UUID")
     */
    public $id;

    /**
     * @var Event[]
     * @ORM\OneToMany(targetEntity="EventBundle\Entity\Event",mappedBy="repeatingEvent")
     */
    public $events;

    /**
     * @ORM\Column(type="smallint")
     */
    public $type;

    /**
     * @ORM\Column(type="string",length=255)
     */
    public $name;

    /**
     * @ORM\Column(type="datetime",nullable=true)
     * @var \DateTime
     */
    public $start;

    /**
     * @ORM\Column(type="string",length=255,nullable=true)
     */
    public $location;

    /**
     * @ORM\Column(type="text",nullable=true)
     */
    public $info;

    /**
     * @ORM\Column(type="datetime")
     * @var \DateTime
     */
    public $created;

    /**
     * @ORM\Column(type="datetime")
     * @var \DateTime
     */
    public $updated;


    /**
     * @ORM\Column(type="string",length=255,nullable=true)
     */
    public $createdBy;

    /**
     * @ORM\Column(type="string",length=255,nullable=true)
     */
    public $updatedBy;


    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\User")
     * @var User
     */
    public $owner;

    /**
     * @ORM\Column(type="boolean")
     */
    public $disableImpulse=false;

    /**
     * @ORM\Column(type="integer",nullable=true)
     */
    public $maxPersons = 0;


    /**
     * @ORM\Column(type="boolean",nullable=true)
     */
    public $public;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Group")
     */
    public $group;

    /**
     * @ORM\Column(type="boolean")
     */
    public $disableAnswer=false;

    /**
     * @var User[]
     * @ORM\ManyToMany(targetEntity="App\Entity\User")
     *  @ORM\JoinTable(name="repeatevent_notifications",
     *      joinColumns={@ORM\JoinColumn(name="repeat_event_id", referencedColumnName="id",columnDefinition="char(36) COLLATE utf8_unicode_ci")},
     *      inverseJoinColumns={@ORM\JoinColumn(name="user_id",referencedColumnName="id")}
     *      )
     */
    public $notifications;

    public function __construct()
    {
        $this->created = new \DateTime();
        $this->updated = new \DateTime();
        $this->events = array();
    }

    /**
     * @ORM\PreUpdate()
     */
    public function onUpdate()
    {
        $this->updated = new \DateTime();
    }


    public function getFormattedDate($format){
        if(!$this->start instanceof \DateTime){
            return 'In Planung';
        }else{
            setlocale(LC_ALL,'de_DE');
            return strftime($format,$this->start->getTimestamp());
        }
    }

    public function getTypeAsText(){
        $list = array_flip(RepeatingType::getList());
        return $list[$this->type];
    }

    public function getInterval()
    {
        if($this->type == RepeatingType::WEEKLY){
            return new \DateInterval("P7D");
        }elseif($this->type == RepeatingType::SECONDWEEKLY){
            return new \DateInterval("P14D");
        }elseif($this->type == RepeatingType::THIRDWEEKLY){
            return new \DateInterval("P21D");
        }elseif($this->type == RepeatingType::FOURWEEKLY){
            return new \DateInterval("P28D");
        }elseif($this->type == RepeatingType::MONTHLY){
            return new \DateInterval("P1M");
        }
    }

    public function getFutureEvents(\DateTime $start, $hideArchived = false){
        return array_filter($this->events->toArray(),function($event) use($start,$hideArchived){
            if($hideArchived && $event->archived){
                return false;
            }
            return $event->date > $start;
        });
    }

    public function userBecomesNotification(UserInterface $user){
        return array_search($user,$this->notifications->toArray());
    }
}

bundles/EventBundle/Controller/RepeatingEventController.php
<?php

namespace EventBundle\Controller;

use App\Entity\Comment;
use EventBundle\Entity\RepeatingEvent;
use EventBundle\Entity\RepeatingEventVote;
use App\Form\CommentFormType;
use EventBundle\RepeatingEvent\RepeatingEventDeletedRepeatingEvent;
use EventBundle\RepeatingEvent\RepeatingEventEditedRepeatingEvent;
use EventBundle\Form\RepeatingEventFormType;
use EventBundle\RepeatingEvent\RepeatingEventAnsweredRepeatingEvent;
use EventBundle\RepeatingEvent\RepeatingEventCommentedRepeatingEvent;
use EventBundle\RepeatingEvent\RepeatingEventCreatedRepeatingEvent;
use EventBundle\RepeatingEvent\RepeatingEventSharedRepeatingEvent;
use EventBundle\Services\RepeatingEvents;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\HttpFoundation\Request;

class RepeatingEventController extends AbstractController
{

    /**
     * @Route("/repeatingEvent/create", name="repeatingEvent_create")
     * @IsGranted("ROLE_REPEATINGEVENT_CREATE")
     * @param Request $request
     * @return \Symfony\Component\HttpFoundation\Response
     */
    public function create(Request $request)
    {
        setlocale(LC_TIME, "de_DE");
        $repeatingEvent = new RepeatingEvent();
        $form = $this->createForm(RepeatingEventFormType::class, $repeatingEvent);
        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {

            $repeatingEvent->createdBy = $this->getUser()->getUsername();
            $repeatingEvent->updatedBy = $this->getUser()->getUsername();
            $repeatingEvent->owner = $this->getUser();
            $em = $this->getDoctrine()->getManager();
            $em->persist($repeatingEvent);
            $em->flush();

            $service = new RepeatingEvents($this->getDoctrine()->getManager());
            $service->updateEvents($repeatingEvent);

            $this->addFlash('success', 'Serientermin wurde gespeichert!');
            return $this->redirectToRoute('event');
        }
        return $this->render('closed_area/RepeatingEvent/form.html.twig', ['form' => $form->createView(), 'page_title' => 'Serientermin hinzufügen']);
    }


    /**
     * @Route("/repeatingEvent/edit/{repeatingEvent}", name="repeatingEvent_edit")
     * @IsGranted("ROLE_REPEATINGEVENT_EDIT")
     * @param Request $request
     * @return \Symfony\Component\HttpFoundation\Response
     */
    public function edit(RepeatingEvent $repeatingEvent, Request $request)
    {
        $form = $this->createForm(RepeatingEventFormType::class, $repeatingEvent);
        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {
            $repeatingEvent->updatedBy = $this->getUser()->getUsername();
            $em = $this->getDoctrine()->getManager();
            $em->persist($repeatingEvent);
            $em->flush();


            $service = new RepeatingEvents($this->getDoctrine()->getManager());
            $service->updateEvents($repeatingEvent);
            $this->addFlash('success', 'Serientermin wurde gespeichert!');
            return $this->redirectToRoute('event');
        }
        return $this->render('closed_area/RepeatingEvent/form.html.twig', ['form' => $form->createView(), 'page_title' => 'Serientermin bearbeiten']);
    }

    /**
     * @Route("/repeatingEvent/delete/{repeatingEvent}/{confirm}", name="repeatingEvent_delete",defaults={"confirm"=false})+-
     * @IsGranted("ROLE_REPEATINGEVENT_DELETE")
     * @param Request $request
     * @return \Symfony\Component\HttpFoundation\Response
     */
    public function delete(RepeatingEvent $repeatingEvent, $confirm = false, Request $request)
    {
        if ($confirm == false) {
            return $this->render('closed_area/confirm.html.twig', ['type' => 'Serientermin']);
        }
        $em = $this->getDoctrine()->getManager();
        $em->remove($repeatingEvent);
        $em->flush();
        $this->addFlash('success', 'Serientermin wurde gelöscht!');
        return $this->redirectToRoute('repeatingEvent');

    }

    /**
     * @Route("/repeatingEvent/view/{repeatingEvent}", name="repeatingEvent_view")
     * @param Request $request
     * @return \Symfony\Component\HttpFoundation\Response
     */
    public function view(RepeatingEvent $repeatingEvent, Request $request)
    {

        $futureEvents = $repeatingEvent->getFutureEvents(new \DateTime());

        return $this->render('closed_area/RepeatingEvent/view.html.twig', ['event' => $repeatingEvent,'events'=>$futureEvents]);
    }

    /**
     * @Route("/repeatingEvent/share/{repeatingEvent}", name="repeatingEvent_share")
     * @param repeatingEvent $repeatingEvent
     * @param Request $request
     */
    public function share(repeatingEvent $repeatingEvent, Request $request)
    {
        if ($repeatingEvent->permission == 0) {
            $this->get('repeatingEvent_dispatcher')->dispatch(new RepeatingEventSharedRepeatingEvent($repeatingEvent, $this->getUser()));
            $this->addFlash('success', 'Serientermin wurde geteilt!');
        } else {
            $this->addFlash('danger', 'Teilen nicht möglich! Sichtbarkeit ist eingeschränkt!');
        }
        return $this->redirectToRoute('repeatingEvent_view', ['repeatingEvent' => $repeatingEvent->id]);
    }




}

templates/gemeinsam_bewegen/closed_area/RepeatingEvent/form.html.twig
{% extends 'closed_area/base.html.twig' %}
{% block content_row %}
    <div class="container container-fluid" id="home">
        <!-- HOME -->

        <!-- ABOUT & UPDATES -->
        <div class="row-fluid" id="about">
            {{ form_start(form) }}
            <div class="span12">
                <h2 class="page-title" id="scroll_up"> {{ page_title }}</h2>
                {{ form_widget(form) }}
            </div>
            <div class="alert-warning"><strong>Hinweis:</strong> Alle Änderungen werden in Termine übernommen, bei denen Zeit oder Ort nicht manuell geändert wurden.</div><br>
            <button type="submit" class="btn btn-success" name="_submit">speichern</button>
            <a href="{{ path('event') }}" class="btn btn-default" name="_submit">zurück</a>
            {{ form_end(form) }}
        </div>


    </div>
{% endblock %}

templates/gemeinsam_bewegen/closed_area/RepeatingEvent/view.html.twig
{% extends 'closed_area/base.html.twig' %}
{% block content_row %}
    <div class="row-fluid">
        <div class="col-sm-12">
            <div class="row">
                <div class="col-sm-12">
                    <h2 class="page-title" id="scroll_up"> Serientermin {{ event.name }}</h2>
                    <a href="{{ path('event') }}" class="btn btn-sm btn-default" name="_submit"><span
                                class="glyphicon glyphicon-backward"></span> zurück</a>
                    {% if is_granted('ROLE_REPEATINGEVENT_EDIT') %}
                    <a href="{{ path('repeatingEvent_edit',{repeatingEvent:event.id}) }}" class="btn btn-sm btn-warning"><span
                                class="glyphicon glyphicon-pencil"></span> bearbeiten</a>
                    {% endif %}
                    {% if is_granted('ROLE_REPEATINGEVENT_DELETE') %}
                    <a href="{{ path('repeatingEvent_delete',{repeatingEvent:event.id}) }}" class="btn btn-sm btn-danger"><span
                                class="glyphicon glyphicon-trash"></span> löschen</a>
                    {% endif %}
                    <br><br>
                </div>
            </div>
            <div class="bg-light rounded m-3 p-3">
                <div class="row voffset5">
                    <div class="col-sm-2 font-weight-bold">Datum:</div>
                    <div class="col-sm-10">{{ event.getFormattedDate('%d.%m.%Y %H:%M') }}</div>
                </div>
                <div class="row voffset5">
                    <div class="col-sm-2 font-weight-bold">Typ:</div>
                    <div class="col-sm-10">{{ event.typeAsText|trans([],'event') }}</div>
                </div>
                <div class="row voffset3">
                    <div class="col-sm-2 font-weight-bold">Name:</div>
                    <div class="col-sm-10">{{ event.name }}</div>
                </div>
                <div class="row voffset3">
                    <div class="col-sm-2 font-weight-bold">Ort:</div>
                    <div class="col-sm-10">{{ event.location }}</div>
                </div>
                <div class="row voffset3">
                    <div class="col-sm-2 font-weight-bold">Info:</div>
                    <div class="col-sm-10">{{ (event.info ~ " ")|raw }}</div>
                </div>
                <div class="row voffset3">
                    <div class="col-sm-2 font-weight-bold">Antworten abschalten:</div>
                    <div class="col-sm-10">{{ event.disableAnswer ? 'Ja' : 'Nein' }}</div>
                </div>
                <div class="row voffset3">
                    <div class="col-sm-2 font-weight-bold">Spontan abschalten:</div>
                    <div class="col-sm-10">{{ event.disableImpulse ? 'Ja' : 'Nein' }}</div>
                </div>
                <div class="row voffset3">
                    <div class="col-sm-2 font-weight-bold">Öffentlich:</div>
                    <div class="col-sm-10">{{ event.public ? 'Ja' : 'Nein' }}</div>
                </div>
                {% if event.updated is defined and event.updated.timestamp > 100 %}
            <br><br>
                <small>Letzte Änderung von {{ event.updatedBy }} am {{ event.updated|date('d.m.y') }}
                    um {{ event.updated|date('H:i') }}</small>
                {% endif %}<br><br>
            </div>
            {% include 'closed_area/Event/list.html.twig' %}
        </div>
    </div>

{% endblock %}