src/Entity/User.php
<?php
/**
 * Created by PhpStorm.
 * User: Tim
 * Date: 24.07.2017
 * Time: 14:49
 */

namespace App\Entity;


use CompanyBundle\Entity\Company;
use FOS\UserBundle\Model\User as BaseUser;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity
 * @ORM\Table(name="fos_user")
 * @ORM\HasLifecycleCallbacks()
 */
class User extends BaseUser
{
    /**
     * @ORM\Id
     * @ORM\Column(type="integer")
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    protected $id;

    /**
     * @ORM\Column(type="string",length=255,nullable=true)
     */
    public $telegramUsername;


    /**
     * @ORM\Column(type="string",length=255,nullable=true)
     */
    public $telegramChatId;

    /**
     * @var Company
     * @ORM\ManyToOne(targetEntity="CompanyBundle\Entity\Company")
     */
    public $company;

    /**
     * @ORM\Column(type="string",length=255,nullable=true)
     */
    public $firstname;

    /**
     * @ORM\Column(type="string",length=255,nullable=true)
     */
    public $lastname;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\Group",inversedBy="users")
     * @ORM\JoinTable(name="fos_user_user_group",
     *      joinColumns={@ORM\JoinColumn(name="user_id", referencedColumnName="id")},
     *      inverseJoinColumns={@ORM\JoinColumn(name="group_id", referencedColumnName="id")}
     * )
     */
    protected $groups;

    /**
     * @ORM\Column(type="smallint",nullable=true)
     */
    public $approval;

    /**
     * @var array
     * @ORM\Column(type="simple_array",nullable=true)
     */
    public $mails;


    public function __construct()
    {
        parent::__construct();
        // your own logic
    }

    /**
     * @ORM\PrePersist
     */
    public function disable()
    {
        $this->setEnabled(false);
    }

    public function telegramSupported()
    {
        if (strlen((string)$this->telegramChatId) > 0) {
            return true;
        } else {
            return false;
        }
    }

    public function getPublicGroups()
    {
        return array_filter($this->groups->toArray(),function($group){
            return $group->public;
        });
    }

    private function getNotPublicGroups()
    {
        return array_filter($this->groups->toArray(),function($group){
            return $group->public !== true;
        });
    }

    public function setPublicGroups($groups)
    {
        $this->groups = array_merge($groups,$this->getNotPublicGroups());
    }

}

templates/gemeinsam_bewegen/closed_area/base.html.twig
<!DOCTYPE html>
<html lang="de">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{{ page_title }}</title>
        {% block head_style %}
            {{ encore_entry_link_tags('gemeinsam_bewegen/closed_area') }}
        {% endblock head_style %}


{% block body_tag %}
<body>
{% endblock body_tag %}


<div class="cover-container d-flex w-100 h-100 p-3 mx-auto flex-column">
    <header class="masthead">
        <div class="inner">
        <div class="row">      <div class="col-md-12">

            <a href="{{ path('home') }}"><img class="masthead-brand" src="{{ asset('build/images/gemeinsambewegen.png') }}" /></a>
                <div class="headleft"></div>
                <div class="headleftB"></div>
                <div class="headright"></div>
                <div class="headrightMid"></div>
                <div class="headrightLeft"></div>
        </div>
        </div>

        </div>
        <div class="row">
            <div class="col-md-12">
                {% block navbar %}
                    {% include 'closed_area/navbar.html.twig' %}
                {% endblock navbar %}

            </div>
        </div>
    </header>
    {% block flashes %}

        {% for label, messages in app.flashes() %}
            {% for message in messages %}
                <div class="row">
                    <div class="col-sm-12 voffset5">
                        <div class="alert alert-{{ label }}">
                            {{ message }}
                        </div>
                    </div>
                </div>
            {% endfor %}
        {% endfor %}
    {% endblock flashes %}
    {% block content_row %}
    {% endblock %}
    <footer class="mastfoot mt-auto text-center">
        <div class="inner">
            <p><a href="{{ path('impressum') }}">Impressum</a> | <a href="{{ path('datenschutz') }}">Datenschutzerklärung</a></p>
        </div>
    </footer>
</div>
{{ encore_entry_script_tags('gemeinsam_bewegen/closed_area') }}
{% block endscripts %}
{% endblock %}
</body>
</html>

templates/gemeinsam_bewegen/closed_area/confirm.html.twig
{% extends 'closed_area/base.html.twig' %}
{% block content_row %}
    <div class="container container-fluid" id="home">
        <!-- HOME -->

        <!-- ABOUT & UPDATES -->
        <div class="row-fluid" id="about">
            <div class="span12">
                <h2 class="page-title" id="scroll_up">Löschen bestätigen</h2>

                {{ type }} wirklich löschen?<br><br>
                <a class="btn btn-default" href="javascript:history.back()">Nein, zurück</a><br><br>
                <a class="btn btn-danger" href="{{ path(app.request.attributes.get('_route'),
                app.request.attributes.get('_route_params')) }}/1">Ja, löschen</a>

            </div>

        </div>


    </div>
{% endblock %}

templates/gemeinsam_bewegen/closed_area/homescreen.html.twig
{% extends 'closed_area/base.html.twig' %}
{% block content_row %}

    <div class="container container-fluid visible-lg" id="home">
        <div class="row">
        {{ widgetservice.renderedWidgets|raw }}
        </div>
    </div>


{% endblock %}

templates/gemeinsam_bewegen/closed_area/navbar.html.twig
<nav class="navbar navbar-expand-md navbar-dark">
    <button class="navbar-toggler collapsed" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="navbar-collapse collapse" id="navbarsExampleDefault" style="">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item">
                <a class="nav-link" href="{{ path('homepage') }}">Übersicht</a>
            </li>

            {{ menuservice.renderedMenu|raw }}
            {% if is_granted('ROLE_USER_VIEWLIST') or is_granted('ROLE_COMPANY_VIEWLIST') or is_granted('ROLE_GROUP_VIEWLIST')  %}
                <li class="nav-item dropdown" data-dropdown="dropdown">
                    <a class="nav-link dropdown-toggle" href="#" class="dropdown-toggle" data-toggle="dropdown" role="button">Administration <span class="caret"></span></a>
                    <ul class="dropdown-menu" role="menu">
                        {% if is_granted('ROLE_USER_VIEWLIST') %}<a class="dropdown-item" href="{{ path('userlist') }}">Benutzer</a>{% endif %}
                        {% if is_granted('ROLE_COMPANY_VIEWLIST') %}<a class="dropdown-item" href="{{ path('company') }}">Firmen</a>{% endif %}
                        {% if is_granted('ROLE_GROUP_VIEWLIST') %}<a class="dropdown-item" href="{{ path('group') }}">Gruppen</a>{% endif %}
                    </ul>
                </li>
            {% endif %}
            <li class="nav-item dropdown" data-dropdown="dropdown">
                <a class="nav-link dropdown-toggle" href="#" class="dropdown-toggle" data-toggle="dropdown" role="button"> <span class="glyphicon glyphicon-user"></span> {{ app.user.username }} <span class="caret"></span></a>
                <ul class="dropdown-menu" role="menu">
                    <a class="dropdown-item" href="{{ path('settings') }}">Einstellungen</a>
                    <a class="dropdown-item" href="{{ path('public_groups') }}">Meine Gruppen</a>
                    <a class="dropdown-item" href="{{ path('fos_user_security_logout') }}">abmelden</a>
                </ul>
            </li>
        </ul>

    </div>
</nav>

templates/gemeinsam_bewegen/closed_area/publicgroups.html.twig
{% extends 'closed_area/base.html.twig' %}

{% form_theme form _self %}

{% block checkbox_widget -%}
    {%- set parent_label_class = parent_label_class|default(label_attr.class|default('')) -%}
    {%- if 'checkbox-custom' in parent_label_class -%}
        {%- set attr = attr|merge({class: (attr.class|default('') ~ ' custom-control-input')|trim}) -%}
        <div class="custom-control custom-checkbox{{ 'checkbox-inline' in parent_label_class ? ' custom-control-inline' }}">
            {{ block('checkbox_widget_base') }}
        </div>
    {%- else -%}
        {%- set attr = attr|merge({class: (attr.class|default('') ~ ' form-check-input')|trim}) -%}
        {{ block('checkbox_widget_base') }}
    {%- endif -%}
{%- endblock checkbox_widget %}

{%- block checkbox_widget_base -%}
    <input type="checkbox" {{ block('widget_attributes') }}{% if value is defined %} value="{{ value }}"{% endif %}{% if checked %} checked="checked"{% endif %} />
{%- endblock checkbox_widget_base -%}

{% block checkbox_label %}
    {# {% block _user_registration_form_termsAccepted_label %} - use this if you need it for just a single field, amend accordingly to your form type/field #}
    {#- pulled from bootstrap_4_layout.html.twig and appended |raw to the end of label line -#}
    {% set is_parent_custom = parent_label_class is defined and ('checkbox-custom' in parent_label_class or 'radio-custom' in parent_label_class) %}
    {% set is_custom = label_attr.class is defined and ('checkbox-custom' in label_attr.class or 'radio-custom' in label_attr.class) %}
    {%- if is_parent_custom or is_custom -%}
        {%- set label_attr = label_attr|merge({class: (label_attr.class|default('') ~ ' custom-control-label')|trim}) -%}
    {%- else %}
        {%- set label_attr = label_attr|merge({class: (label_attr.class|default('') ~ ' form-check-label')|trim}) -%}
    {%- endif %}
    {%- if not compound -%}
        {% set label_attr = label_attr|merge({'for': id}) %}
    {%- endif -%}
    {%- if required -%}
        {%- set label_attr = label_attr|merge({class: (label_attr.class|default('') ~ ' required')|trim}) -%}
    {%- endif -%}
    {%- if parent_label_class is defined -%}
        {%- set label_attr = label_attr|merge({class: (label_attr.class|default('') ~ ' ' ~ parent_label_class)|replace({'checkbox-inline': '', 'radio-inline': '', 'checkbox-custom': '', 'radio-custom': ''})|trim}) -%}
    {%- endif -%}
    {%- if label is not same as(false) and label is empty -%}
        {%- if label_format is not empty -%}
            {%- set label = label_format|replace({
                '%name%': name,
                '%id%': id,
            }) -%}
        {%- else -%}
            {%- set label = name|humanize -%}
        {%- endif -%}
    {%- endif -%}
    <label{% for attrname, attrvalue in label_attr %} {{ attrname }}="{{ attrvalue }}"{% endfor %}>
    {{- label is not same as(false) ? (translation_domain is same as(false) ? label : label|trans({}, translation_domain)) -}}
    {{- form_errors(form) -}}
    </label>
{% endblock %}

{% block content_row %}
    <div class="container container-fluid" id="home">
        <!-- HOME -->

        <!-- ABOUT & UPDATES -->
        <div class="row-fluid" id="about">
            {{ form_start(form) }}
            <div class="span12">
                <h2 class="page-title" id="scroll_up">Meine Gruppen</h2>


                    <div class="funkyradio">
                        {% for child in form.publicGroups %}
                            <div class="funkyradio-success">
                                {{ form_widget(child) }}
                                {{ form_label(child) }}
                            </div>
                        {% endfor %}
                    </div>
            </div>
            <br><br>
                <button type="submit" class="btn btn-success" name="_submit">speichern</button>
                {{ form_end(form) }}
               


        </div>


    </div>
{% endblock %}

templates/gemeinsam_bewegen/closed_area/settings.html.twig
{% extends 'closed_area/base.html.twig' %}
{% block content_row %}
    <div class="container container-fluid" id="home">
        <!-- HOME -->

        <!-- ABOUT & UPDATES -->
        <div class="row-fluid" id="about">
            {{ form_start(form) }}
            <div class="span12">
                <h2 class="page-title" id="scroll_up">Einstellungen</h2>
                    {{ form_widget(form) }}
            </div>
                <button type="submit" class="btn btn-success" name="_submit">speichern</button>
                {{ form_end(form) }}
               


        </div>


    </div>
{% endblock %}